### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/EmojisPlus#3]
@Taki21 we need to add the rest of the emojis to the "chat format" detector thing.

**Comment by Taki21** [comment]
xD Ok First I gotta now: how in da world do u do dat!? I mean, where did u get the "heart" strings etc?

**Comment by ImagicalGamer** [comment]
No where, if the players message is ":HEART: set the message to the heart emoji. Idk how to replace the ":HEART:" and have the rest of the message.

**Comment by Taki21** [comment]
use str_replace like
`str_replace(...);`
But I am thinking to use this strategt in another BRANCH without setMessage so it will automatically convert:
like:
If Someone does : 
Hello :HEART: 
They can talk with emoji as well

**Comment by ImagicalGamer** [comment]
Yea dats what I want xD

**Comment by ImagicalGamer** [comment]
Oops xD
